<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <RootNamespace>i26.AspNetCore.Tests</RootNamespace>
        <AssemblyName>i26.AspNetCore.Tests</AssemblyName>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <RollForward>Major</RollForward>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\i26.Core\i26.Core.csproj" />
        <ProjectReference Include="..\..\src\i26.AspNetCore\i26.AspNetCore.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
